export const Character = {
  name: String,
  species: String,
  gender: String,
  house: String,
  dateOfBirth: Date,
  yearOfBirth: Number,
  wizard: Boolean,
  ancestry: String,
  eyeColour: String,
  hairColour: String,
  wand: {
    wood: String,
    core: String,
    length: Number,
  },
  patronus: String,
  hogwartsStudent: Boolean,
  hogwartsStaff: Boolean,
  actor: String,
  alternate_actors: [],
  alive: String,
  image: String,
};
